"""Create editable, reference-styled predictor tables from frozen CSV metrics.

No fitting, checkpoint reads, target reads, or changes to Manuscript.tex.
LaTeX compilation is a separate step; all displayed cells share the CSV source.
"""
from __future__ import annotations

import csv
import hashlib
import json
import math
from pathlib import Path, PureWindowsPath

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = ROOT / "tables/predictor/generated"
RESULTS = ROOT / "tables/predictor/results"
BB = ROOT / "analysis/predictor_supervision/bbbc047/results/frozen_evaluation"
SC = ROOT / "analysis/predictor_supervision/sci_plex3/results/confirmation"
F5 = ROOT / "tables/predictor/inputs/arm_estimates"
# Outputs were first generated on Windows; keep their bytes platform-independent.
CRLF = "\r\n"
METRICS = ("full_target_pcc", "delta_pcc", "raw_target_rmse")
# Perturbation specificity E is the paper's primary endpoint elsewhere, so the
# main BBBC047 table reports it alongside the reconstruction metrics.
BB_METRICS = ("full_target_pcc", "delta_pcc", "raw_target_rmse", "E")
SURFACES = ("cross_cell_unseen", "cross_cell_seen")
LINES = ("A549", "K562", "MCF7")
RAW = "M0_RawAggregate"
CFRA = "M1_CFRA1Aggregate"
RES = "M2_CFRA1Residual"
# Complete sci-Plex3 arm matrix for the Supplementary boundary table.
SC_SURFACES = ("own_cell_unseen", "cross_cell_unseen", "cross_cell_seen")
SC_METRICS = ("full_target_pcc", "delta_pcc", "E")


def read(path):
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def assert_close(a, b, label):
    if not math.isclose(float(a), float(b), rel_tol=0, abs_tol=2e-10):
        raise AssertionError(f"{label}: {a} != {b}")


def record(dataset, setting, line, n, metric, method, raw, cfra, diff):
    assert_close(cfra[0] - raw[0], diff[0], "paired difference")
    for trio in (raw, cfra, diff):
        assert all(math.isfinite(v) for v in trio)
        assert trio[1] <= trio[2]
    return dict(dataset=dataset, setting=setting, target_line=line, n_compounds=n,
        metric=metric, comparator_method=method, raw_mean=raw[0], raw_ci_low=raw[1],
        raw_ci_high=raw[2], comparator_mean=cfra[0], comparator_ci_low=cfra[1],
        comparator_ci_high=cfra[2], difference=diff[0], difference_ci_low=diff[1],
        difference_ci_high=diff[2], bootstrap_draws=10000,
        ci_unit="compound" if dataset == "BBBC047" else "drug_within_target_line",
        ci_status="pointwise_95_percent",
        preferred_direction="lower" if metric=="raw_target_rmse" else "higher",
        metric_status="posthoc_frozen_prediction_supplement" if metric=="raw_target_rmse" else "original_frozen_endpoint")


def load_data():
    inputs = [BB / "TEST_METHOD_SUMMARY.csv", BB / "TEST_CONTRASTS.csv",
        SC / "SURFACE_MACRO_FULL_COMPARISON.csv", SC / "CONFIRMATION_CONTRASTS_ALL.csv",
        F5 / "bc_sciplex3_arm_means_and_ci.csv", F5 / "data_audit.json",
        ROOT / "tables/predictor/inputs/rmse/RMSE_SUMMARY.csv", ROOT / "tables/predictor/inputs/rmse/RMSE_AUDIT.json"]
    bba = {(int(r["budget"]), r["method"]):r for r in read(inputs[0])}
    bbc = {(int(r["budget"]), r["metric"]):r for r in read(inputs[1])}
    macro = {(r["surface"],r["metric"]):r for r in read(inputs[2])}
    contrasts = {(r["surface"],r["target_cell_line"],r["metric"]):r
        for r in read(inputs[3]) if r["comparison"] == CFRA + " - " + RAW}
    own = {(r["surface"],r["target_cell_line"],r["metric"],r["method"]):r
        for r in read(inputs[4]) if r["method"] in (RAW,CFRA)}
    rmse = {(r["dataset"],r["setting"],r["target_line"]):r for r in read(inputs[6])}
    rmse_audit = json.loads(inputs[7].read_text(encoding="utf-8"))
    assert rmse_audit["status"]=="PASS" and rmse_audit["no_sqrt_of_aggregate_mse"]
    assert rmse_audit["summary_sha256"]==sha(inputs[6])
    # The own-arm CI file was generated by replaying the frozen macro indices.
    prior = json.loads(inputs[5].read_text(encoding="utf-8"))
    assert prior["status"] == "PASS" and prior["paired_frozen_means_and_ci_verified"]
    for p in (inputs[0], inputs[1], inputs[2]):
        # Audit paths were recorded on Windows; parse them portably.
        matching = [r for r in prior["source_files"] if PureWindowsPath(r["path"]).name == p.name]
        assert len(matching) == 1 and matching[0]["sha256"] == sha(p)

    def arm(r, metric=None):
        if metric:
            return tuple(float(r[metric + suffix]) for suffix in ("_mean","_ci_low","_ci_high"))
        return tuple(float(r[k]) for k in ("mean","ci_low","ci_high"))

    def rmse_record(dataset,setting,line):
        r=rmse[(dataset,setting,line)]
        a=tuple(float(r[k]) for k in ("raw_mean","raw_ci_low","raw_ci_high"))
        b=tuple(float(r[k]) for k in ("comparator_mean","comparator_ci_low","comparator_ci_high"))
        d=tuple(float(r[k]) for k in ("difference","difference_ci_low","difference_ci_high"))
        return record(dataset,setting,line,int(r["n_compounds"]),"raw_target_rmse",r["comparator_method"],a,b,d)

    main, extended, sciplex = [], [], []
    for budget in (2,3,4):
        for metric in BB_METRICS:
            if metric=="raw_target_rmse":
                main.append(rmse_record("BBBC047",f"{budget}R",""))
                continue
            raw = bba[(budget,"M0_RawKAggregate")]
            m2 = bba[(budget,"M2_CFRA1ViewAggregate_Residual")]
            delta = bbc[(budget,metric)]
            # E requires matched foreign references, so its eligible set is smaller.
            n = int(raw["E_n"]) if metric == "E" else int(raw["n_compounds"])
            assert int(delta["n_compounds"]) == n
            main.append(record("BBBC047",f"{budget}R","",n,metric,
                "CFRA+Res",arm(raw,metric),arm(m2,metric),
                tuple(float(delta[k]) for k in ("estimate","ci_low","ci_high"))))
    for surface in SC_SURFACES:
        for metric in SC_METRICS:
            m = macro[(surface,metric)]
            assert m["n_target_lines"] == "3"
            row = dict(dataset="sci-Plex3", surface=surface, historical_status=m["historical_status"],
                n_drugs_per_target_line=int(m["n_drugs_macro_basis"]), metric=metric,
                raw_mean=float(m[RAW+"_value"]), reca_mean=float(m[CFRA+"_value"]),
                reca_res_mean=float(m[RES+"_value"]))
            for arm_key, prefix in (("reca", "M1_minus_M0"), ("reca_res", "M2_minus_M0")):
                trio = tuple(float(m[prefix+s]) for s in ("_estimate","_ci_low","_ci_high"))
                assert all(math.isfinite(v) for v in trio) and trio[1] <= trio[2]
                assert_close(row[arm_key+"_mean"] - row["raw_mean"], trio[0], prefix)
                row.update({arm_key+"_minus_raw": trio[0], arm_key+"_minus_raw_ci_low": trio[1],
                            arm_key+"_minus_raw_ci_high": trio[2]})
            row.update(bootstrap_draws=int(m["bootstrap_draws"]), ci_unit="drug_within_target_line",
                       ci_status="pointwise_95_percent", preferred_direction="higher",
                       metric_status="original_frozen_endpoint")
            sciplex.append(row)
    for surface in SURFACES:
        setting = "Unseen" if surface.endswith("unseen") else "Seen"
        n = 36 if setting == "Unseen" else 183
        for line in LINES:
            for metric in METRICS:
                if metric=="raw_target_rmse":
                    extended.append(rmse_record("sci-Plex3",setting,line))
                    continue
                r = own[(surface,line,metric,RAW)]
                c = own[(surface,line,metric,CFRA)]
                d = contrasts[(surface,line,metric)]
                assert int(d["n_drugs"]) == n
                extended.append(record("sci-Plex3",setting,line,n,metric,"CFRA",
                    arm(r),arm(c),tuple(float(d[k]) for k in ("estimate","ci_low","ci_high"))))
    assert len(main) == 12 and len(extended) == 18 and len(sciplex) == 9
    assert all(r["dataset"] == "BBBC047" for r in main)
    assert set(r["metric"] for r in main) == set(BB_METRICS)
    assert set(r["metric"] for r in extended) == set(METRICS)
    assert all(r["comparator_method"] == "CFRA" for r in extended)
    audit = dict(status="PASS",main_rows=len(main),supplement_rows=len(extended),
        sciplex_matrix_rows=len(sciplex),
        main_table_datasets=["BBBC047"],
        bbbc047_displayed_arms=["Raw (M0)","ReCA+Res (M2)"],
        bbbc047_displayed_metrics=["PCC","deltaPCC","RMSE","E"],
        sciplex_matrix_surfaces=list(SC_SURFACES),
        sciplex_matrix_arms=["Raw (M0)","ReCA (M1)","ReCA+Res (M2)"],
        sciplex_matrix_metrics=["PCC","deltaPCC","E"],
        celllines_table_arms=["Raw (M0)","ReCA (M1)"],original_results_unchanged=True,
        own_arm_ci_in_every_source_record=True,paired_ci_in_every_source_record=True,
        main_display_rows=6,supplement_display_rows=18,
        main_difference_rows_displayed=False,main_differences_moved_to_supplement=False,
        sciplex_own_ci_source="previous audited replay of frozen within-line macro bootstrap indices",
        no_training_or_selection=True,supplementary_rmse_added=True,
        frozen_correlation_values_and_cis_unchanged=True,
        preferred_directions={"PCC":"up","deltaPCC":"up","RMSE":"down"},
        inputs=[dict(path=str(p.relative_to(ROOT)),sha256=sha(p)) for p in inputs])
    return main, extended, sciplex, audit


def number(v, digits, signed=False):
    s = f"{v:+.{digits}f}" if signed else f"{v:.{digits}f}"
    return s.replace("-", r"\ensuremath{-}")


def cell(r, prefix, signed=False, bold=False):
    keys = ("difference","difference_ci_low","difference_ci_high") if prefix == "difference" else (
        prefix+"_mean",prefix+"_ci_low",prefix+"_ci_high")
    digits = 4
    # Never let rounding erase the sign of a nonzero confidence bound.
    while any(r[k] != 0 and round(r[k],digits) == 0 for k in keys):
        digits += 1
    nums = [number(r[k],digits,signed and i==0) for i,k in enumerate(keys)]
    if bold:
        nums[0] = r"\textbf{" + nums[0] + "}"
    return r"\ReCATableCell{" + "}{".join(nums) + "}"


PREAMBLE = r"""% Generated from frozen metrics. Do not edit individual numeric cells.
% Dependencies: booktabs, array, xcolor, colortbl, caption, helvet.
% colortbl and caption must be available in the host document preamble.
% All definitions are local to this input; no resizebox or raster table.
\begingroup
\sffamily
\setlength{\tabcolsep}{2.5pt}
\renewcommand{\arraystretch}{1.0}
\setlength{\aboverulesep}{0pt}
\setlength{\belowrulesep}{0pt}
\arrayrulecolor[gray]{0.4}
\captionsetup{font={small,sf},labelfont=bf,textfont=bf,justification=raggedright,singlelinecheck=false,labelsep=space,skip=7pt}
\newcommand{\ReCATableCell}[3]{\parbox[t]{\linewidth}{\raggedright #1\\[-0.5pt]{\fontsize{7.2}{8.3}\selectfont\color[gray]{0.25}[#2, #3]}}}
\newcommand{\ReCATableHead}[1]{\rule{0pt}{12pt}\textbf{#1}}
\newcommand{\ReCATableStart}{\begin{tabular}{p{17mm}p{12mm}p{25mm}*{3}{p{\dimexpr(\linewidth-54mm-12\tabcolsep)/3\relax}}}}
"""


HEADS = {"full_target_pcc": r"PCC $\uparrow$", "delta_pcc": r"$\Delta$PCC $\uparrow$",
         "raw_target_rmse": r"RMSE $\downarrow$", "E": r"$E$ $\uparrow$"}


def block_header(title, setting_label, metrics=METRICS):
    return "\n".join([
        r"\rowcolor[gray]{0.86}\multicolumn{"+str(3+len(metrics))+r"}{l}{\rule{0pt}{13pt}\textbf{"+title+r"}}\\[4pt]",
        r"\midrule[0.3pt]",
        r"\rowcolor[gray]{0.92}\ReCATableHead{"+setting_label+r"} & \ReCATableHead{\textit{n}} & \ReCATableHead{Method} & "
        +" & ".join(r"\ReCATableHead{"+HEADS[m]+"}" for m in metrics)+r" \\[4pt]",
        r"\midrule[0.5pt]",
    ])


def data_rows(rows, extended=False, show_difference=True, metrics=METRICS):
    lines = []
    prefixes = ("raw", "comparator", "difference") if show_difference else ("raw", "comparator")
    groups = {}
    for r in rows:
        grouping = r["target_line"] if extended else r["setting"]
        groups.setdefault(grouping, {})[r["metric"]] = r
    for group_index, (grouping, by_metric) in enumerate(groups.items()):
        assert set(by_metric) == set(metrics)
        if group_index:
            lines.append(r"\midrule[0.3pt]")
        first = by_metric[metrics[0]]
        for method_index, prefix in enumerate(prefixes):
            # Neutral scenario banding, never a colour encoding of performance.
            if group_index % 2:
                lines.append(r"\rowcolor[gray]{0.96}")
            label = grouping if method_index == 0 else ""
            n = f'{first["n_compounds"]:,}' if method_index == 0 else ""
            method = {"raw":"Raw", "comparator":first["comparator_method"],
                      "difference":r"\textit{Difference}"}[prefix]
            if prefix == "comparator":
                method = {"CFRA":"ReCA", "CFRA+Res":"ReCA+Res"}.get(method, method)
            cells = []
            for metric in metrics:
                r = by_metric[metric]
                better = (r["comparator_mean"] < r["raw_mean"] if metric == "raw_target_rmse"
                          else r["comparator_mean"] > r["raw_mean"])
                tie = r["comparator_mean"] == r["raw_mean"]
                bold = prefix != "difference" and not tie and (
                    (prefix == "comparator" and better) or (prefix == "raw" and not better))
                cells.append(cell(r, prefix, signed=prefix == "difference", bold=bold))
            row_end = r" \\[12pt]" if prefix == prefixes[-1] else r" \\[4pt]"
            lines.append(" & ".join([r"\rule{0pt}{12pt}"+label,n,method]+cells)+row_end)
    return "\n".join(lines)


def main_notes(rows):
    e_n = [f'{r["n_compounds"]:,}' for r in rows if r["metric"] == "E"]
    assert len(e_n) == 3
    return (r"Values are means with pointwise 95\% bootstrap confidence intervals below. $n$ denotes compounds "
        r"evaluated by PCC, $\Delta$PCC and RMSE; $E$ requires matched references from other compounds and was "
        rf"evaluated on {e_n[0]}, {e_n[1]} and {e_n[2]} compounds at 2R, 3R and 4R, respectively. "
        r"PCC, Pearson correlation coefficient computed on full profiles; $\Delta$PCC, Pearson correlation "
        r"coefficient computed on control-subtracted responses; RMSE, root mean squared error; "
        r"$E$, perturbation specificity (Fisher $z$). "
        r"Res, residual prediction. $\uparrow$/$\downarrow$ indicate higher/lower is better. Bold marks the "
        r"better mean within each setting. Target construction, seed aggregation "
        r"and resampling are described in Methods.")


MAIN_START = (r"\newcommand{\ReCATableStart}{\begin{tabular}{p{13mm}p{11mm}p{19mm}"
              r"*{4}{p{\dimexpr(\linewidth-43mm-14\tabcolsep)/4\relax}}}}")


SUPP_NOTES = r"""Raw (M0) and ReCA (M1) are capacity-matched predictors evaluated on the same raw target. Values are means with pointwise 95\% CIs below. $\uparrow$/$\downarrow$ indicate higher/lower is better. Bold denotes the better method mean within each setting, not statistical significance. Difference rows show ReCA minus Raw; negative RMSE differences indicate improvement. Each drug contributes its dose-averaged score from the original five-seed prediction ensemble. $n$ denotes drugs within the indicated target line; the same drug can occur in multiple target-line evaluations.

PCC is full-profile correlation after adding the matched Vehicle baseline; $\Delta$PCC is correlation of the control-subtracted response. RMSE is the square root of each condition's saved MSE, averaged across doses within drug and then drugs, not the square root of the aggregate MSE. It is a supplementary post-hoc metric on frozen outputs, with no refitting. These cross-cell results are historical evaluations. All CIs use 10,000 paired-drug resamples and are not multiplicity-adjusted. Original correlation values and paired intervals are retained; RMSE and own-arm intervals use the saved within-target-line bootstrap indices. Extra precision is retained where rounding would obscure an interval's sign."""


MAIN_TITLE = "Raw-profile prediction with reproducibility-aware supervision"


def main_body(main):
    s = block_header("BBBC047: selected-repeat reconstruction","Budget",BB_METRICS)+"\n"
    s += data_rows(main,show_difference=False,metrics=BB_METRICS)+"\n"
    return s


def make_table(main, supplemental=False):
    title = "Cell-line-resolved sci-Plex3 prediction with ReCA-derived supervision" if supplemental else MAIN_TITLE
    label = "tab:predictor-celllines" if supplemental else "tab:predictor-supervision"
    preamble = PREAMBLE if supplemental else "\n".join(
        MAIN_START if line.startswith(r"\newcommand{\ReCATableStart}") else line for line in PREAMBLE.split("\n"))
    s = preamble + "\n" + r"\begin{table}[p]" + "\n" + r"\centering" + "\n"
    s += r"\caption["+title+r"]{\textbar\enspace "+title+"}\n"+r"\label{"+label+"}\n"
    s += r"\fontsize{8.5}{10}\selectfont"+"\n"+r"\ReCATableStart"+"\n"+r"\toprule[0.7pt]"+"\n"
    if supplemental:
        for i,setting in enumerate(("Unseen","Seen")):
            if i:
                s += "\n"+r"\midrule[0.7pt]"+"\n"
            s += block_header("sci-Plex3: "+setting.lower()+"-drug cross-cell transfer","Target cell")+"\n"
            s += data_rows([r for r in main if r["setting"]==setting],True)+"\n"
    else:
        s += main_body(main)
    s += r"\bottomrule[0.7pt]"+"\n"+r"\end{tabular}"+"\n"
    s += r"\par\vspace{5pt}\begin{minipage}{\linewidth}\fontsize{7.5}{9.2}\selectfont\raggedright"+"\n"
    s += (SUPP_NOTES if supplemental else main_notes(main))+"\n"
    s += r"\end{minipage}"+"\n"+r"\end{table}"+"\n"+r"\endgroup"+"\n"
    return s


def make_inline_table(main):
    """Variant pasted into the single-file Manuscript.tex (manual caption, no caption package)."""
    body = [line for line in PREAMBLE.split("\n")
            if line.startswith(("\\begingroup", "\\sffamily", "\\setlength", "\\renewcommand",
                                "\\arrayrulecolor", "\\newcommand{\\ReCATableCell}", "\\newcommand{\\ReCATableHead}"))]
    s = "\n".join([
        "% BEGIN predictor table integration",
        "% Generated by tables/predictor/scripts/build_predictor_table.py from frozen metrics.",
        "% Do not edit individual numeric cells; regenerate and paste instead.",
        "% Inline submission variant: manual caption avoids changing other figure captions.",
        *body, MAIN_START, "",
        r"\begin{table}[!htbp]", r"\centering",
        r"\refstepcounter{table}\label{tab:predictor-supervision}",
        r"\noindent\makebox[\linewidth][l]{{\fontsize{10}{12}\selectfont\textbf{Table \thetable\enspace|\enspace "
        + MAIN_TITLE + r"}}}\par\vspace{7pt}",
        r"\fontsize{8.5}{10}\selectfont", r"\ReCATableStart", r"\toprule[0.7pt]"]) + "\n"
    s += main_body(main)
    s += r"\bottomrule[0.7pt]"+"\n"+r"\end{tabular}"+"\n"
    s += r"\par\vspace{5pt}\begin{minipage}{\linewidth}\fontsize{8}{10}\selectfont\raggedright"+"\n"
    s += main_notes(main)+"\n"+r"\end{minipage}"+"\n"+r"\end{table}"+"\n"+r"\endgroup"+"\n"
    s += "% END predictor table integration\n"
    return s


SC_LABELS = {"own_cell_unseen": "Within cell line, unseen drugs",
             "cross_cell_unseen": "Across cell lines, unseen drugs",
             "cross_cell_seen": "Across cell lines, seen drugs"}


def sci_value(v, signed=False):
    # Text-mode digits match the sans-serif body; same minus handling as number().
    return number(v, 4, signed)


def make_sciplex_table(rows):
    """Supplementary longtable with every sci-Plex3 surface, arm and metric."""
    by = {(r["surface"], r["metric"]): r for r in rows}
    head = (r"\textbf{Training target} & \textbf{PCC $\uparrow$} & \textbf{$\Delta$PCC $\uparrow$} & "
            r"\textbf{$E$ $\uparrow$} \\")
    s = "\n".join([
        "% Generated by tables/predictor/scripts/build_predictor_table.py from frozen metrics.",
        "% Do not edit individual numeric cells; regenerate and paste instead.",
        r"\subsection*{Supplementary Table S6 | sci-Plex3 prediction with ReCA-derived training targets}",
        r"\begingroup", r"\fontsize{10.5}{12.5}\selectfont", r"\setlength{\tabcolsep}{4pt}",
        r"\renewcommand{\arraystretch}{1.14}",
        r"\begin{longtable}{@{}P{70mm}P{58mm}P{58mm}P{58mm}@{}}", r"\toprule", head, r"\midrule",
        r"\endfirsthead", r"\multicolumn{4}{l}{\textbf{Supplementary Table S6 continued}} \\[4pt]",
        r"\toprule", head, r"\midrule", r"\endhead", r"\bottomrule", r"\endlastfoot"]) + "\n"
    for i, surface in enumerate(SC_SURFACES):
        n = by[(surface, SC_METRICS[0])]["n_drugs_per_target_line"]
        if i:
            s += r"\addlinespace[4pt]" + "\n"
        s += (r"\rowcolor{black!5}\multicolumn{4}{l}{\textbf{" + SC_LABELS[surface]
              + rf" ({n} drugs per target cell line)" + r"}} \\" + "\n")
        for label, key in (("Raw (observed responses)", None), ("ReCA", "reca"), ("ReCA+Res", "reca_res")):
            cells = []
            for metric in SC_METRICS:
                r = by[(surface, metric)]
                if key is None:
                    cells.append(sci_value(r["raw_mean"]))
                else:
                    cells.append(sci_value(r[key + "_mean"]) + r"\newline "
                                 + sci_value(r[key + "_minus_raw"], True) + r" [" + sci_value(r[key + "_minus_raw_ci_low"], True)
                                 + r", " + sci_value(r[key + "_minus_raw_ci_high"], True) + "]")
            s += label + " & " + " & ".join(cells) + r" \\[2pt]" + "\n"
    s += r"\end{longtable}" + "\n" + r"\endgroup" + "\n"
    s += (r"{\fontsize{10.5}{12.5}\selectfont " + SC_NOTES + r"\par}" + "\n")
    return s


SC_NOTES = (r"Values are means over the three held-out target cell lines (A549, K562 and MCF7), each weighted equally. "
    r"For ReCA and ReCA+Res, the second line gives the paired difference from Raw with its pointwise 95\% interval "
    r"(10,000 paired drug resamples within each target cell line). Raw trains on observed responses; ReCA trains "
    r"on direct ReCA estimates; ReCA+Res predicts the ReCA estimate and the observed-minus-ReCA residual in "
    r"separate branches and sums them, as for BBBC047 in Table~3. All arms were capacity-matched and evaluated against the "
    r"same observed target profiles. PCC, full-profile correlation after adding the matched Vehicle baseline; "
    r"$\Delta$PCC, correlation of control-subtracted responses; $E$, perturbation specificity (same-drug minus "
    r"other-drug Fisher-$z$ agreement). With two measurements per condition, the sci-Plex3 ReCA adaptation "
    r"reduces aggregated-target IMR to IMR and uses diagonal shrinkage (Supplementary Methods). Seen-drug "
    r"transfer uses drugs that were also in the source training set.")


def main():
    rows, ext, sciplex, audit = load_data()
    OUT.mkdir(parents=True,exist_ok=True)
    RESULTS.mkdir(parents=True,exist_ok=True)
    for name,data in (("predictor_main_source.csv",rows),("predictor_celllines_source.csv",ext),
                      ("sciplex3_target_matrix_source.csv",sciplex)):
        with (RESULTS/name).open("w",encoding="utf-8",newline="") as f:
            writer=csv.DictWriter(f,fieldnames=list(data[0]))
            writer.writeheader();writer.writerows(data)
    main_tex=make_table(rows)
    ext_tex=make_table(ext,True)
    assert r"\textit{Difference}" not in main_tex
    archived_cellline_table = HERE / "archive_pre_main_difference_removal/table_predictor_celllines.tex"
    if archived_cellline_table.is_file():
        assert ext_tex == archived_cellline_table.read_text(encoding="utf-8")
    inline_tex=make_inline_table(rows)
    sciplex_tex=make_sciplex_table(sciplex)
    # The main table is BBBC047-only; every sci-Plex3 arm appears in the Supplementary matrix.
    assert "sci-Plex3" not in main_tex and "sci-Plex3" not in inline_tex
    for arm in ("Raw (observed responses)", "ReCA &", "ReCA+Res &"):
        assert sciplex_tex.count(arm) == len(SC_SURFACES), arm
    for t in (main_tex,inline_tex):
        assert r"$E$ $\uparrow$" in t and r"PCC $\uparrow$" in t and r"RMSE $\downarrow$" in t
    assert "ReCA+Res" not in ext_tex and "$E$" not in ext_tex
    (OUT/"table_predictor_supervision.tex").write_text(main_tex,encoding="utf-8",newline=CRLF)
    (OUT/"table_predictor_supervision_inline.tex").write_text(inline_tex,encoding="utf-8",newline=CRLF)
    (OUT/"table_sciplex3_target_matrix.tex").write_text(sciplex_tex,encoding="utf-8",newline=CRLF)
    (OUT/"table_predictor_celllines.tex").write_text(ext_tex,encoding="utf-8",newline=CRLF)
    preview=r"""\RequirePackage{fix-cm}
\documentclass[10pt]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{booktabs,array,xcolor,colortbl,amsmath,caption}
\usepackage[paperwidth=183mm,paperheight=235mm,left=5mm,right=5mm,top=6mm,bottom=6mm]{geometry}
\captionsetup{font=small,labelfont=bf,textfont=bf,justification=raggedright,singlelinecheck=false,labelsep=period,skip=8pt}
\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlength{\parskip}{3pt}
\makeatletter
\setlength{\@fptop}{0pt}
\makeatother
\begin{document}
\input{table_predictor_supervision.tex}
\clearpage
\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}
\input{table_predictor_celllines.tex}
\clearpage
\end{document}
"""
    (OUT/"predictor_tables_preview.tex").write_text(preview,encoding="utf-8",newline=CRLF)
    # Temporary proof at the current manuscript's 166-mm text width.
    qa_path = ROOT / "outputs/tables/integration_width_qa.tex"
    qa_path.parent.mkdir(parents=True, exist_ok=True)
    qa_path.write_text(
        preview.replace("paperwidth=183mm", "paperwidth=176mm"),encoding="utf-8",newline=CRLF)
    audit["output_hashes"]={p.name:sha(p) for p in OUT.glob("*.tex") if p.name.startswith(("table_predictor_","predictor_tables_"))}
    audit["reference_style"] = dict(
        layout="metrics_in_columns_methods_in_rows",
        neutral_grey_headers=True, neutral_scenario_banding=True,
        bold_rule="better point estimate within setting and metric",
        references=[dict(filename=p.name,sha256=sha(p),pages=pages) for p,pages in (
            (ROOT / "paper/references/模板1_A machine learning benchmarking framework for lipid nanoparticle transfection efficiency prediction.pdf",[4]),
            (ROOT / "paper/references/模板2_Preferential CDR masking in paired antibody language models improves binding affinity prediction.pdf",[6,7])) if p.is_file()])
    (RESULTS/"table_audit.json").write_text(json.dumps(audit,indent=2),encoding="utf-8",newline=CRLF)
    print(json.dumps({k:v for k,v in audit.items() if k not in ("inputs","output_hashes")},indent=2))


if __name__ == "__main__":
    main()
